---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
        #'org.hibernate.cache.SingletonEhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: update
            url: "jdbc:h2:/Users/shawn/works/mClub/mclub-tracker-server.git/data/main_data_g3;MVCC=TRUE;LOCK_TIMEOUT=10000"
            pooled: false

            ## for mysql
            #pooled=true
            #driverClassName="com.mysql.jdbc.Driver"
            #dialect="org.hibernate.dialect.MySQL5InnoDBDialect"
            #url="jdbc:mysql://localhost:3306/mclub?useUnicode=yes&characterEncoding=UTF-8"
            #username="mclub"
            #password="secret"
            #logSql = true
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:~/mclub-tracker/main_data;MVCC=TRUE;LOCK_TIMEOUT=10000
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 10
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: mclub.tracker
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

server:
    'contextPath': '/mclub'
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

#tracker:
#    gps103:
#        enabled: true
#        port 5001


quartz:
    autoStartup: true
    props:
      scheduler.instanceName: RuleProcessQuartzScheduler
      threadPool.threadCount: 1

environments:
    development:
        quartz:
            autoStartup: true
    test:
        quartz:
            autoStartup: true
    production:
        quartz:
            autoStartup: true