---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        #region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
        #'org.hibernate.cache.SingletonEhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
#    username: sa
#    password:

# Reactor config for the event bus
reactor:
    dispatchers:
        # default executor will create anonymous threads
        threadPoolExecutor:
            type: threadPoolExecutor
            size: 1
            backlog: 128

        # customized executor could create pretty-named threads
#        default: myExecutor
#        myExecutor:
#            type: threadPoolExecutor
#            size: 5
#            backlog: 2048

environments:
    development:
        dataSource:
            dbCreate: update
            url: "jdbc:h2:/Users/shawn/works/mClub/mclub-tracker-server.git/data/main_data_g3;MVCC=TRUE;LOCK_TIMEOUT=10000"
            pooled: false

            ## for mysql
#            pooled: true
#            driverClassName: "com.mysql.jdbc.Driver"
#            dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
#            url: "jdbc:mysql://localhost:3306/mclub?useUnicode=yes&characterEncoding=UTF-8"
#            username: "mclub"
#            password: "secret"
#            logSql: true
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:~/mclub-tracker/main_data;MVCC=TRUE;LOCK_TIMEOUT=10000
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 10
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: mclub.tracker
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

server:
    'contextPath': '/mclub'
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    enabled: false
    health.sensitive: true

    jmx:
        unique-names: true
        enabled: false

#tracker:
#    gps103:
#        enabled: true
#        port 5001


quartz:
    autoStartup: true
    props:
      scheduler.instanceName: RuleProcessQuartzScheduler
      threadPool.threadCount: 1

environments:
    development:
        quartz:
            autoStartup: true
    test:
        quartz:
            autoStartup: true
    production:
        quartz:
            autoStartup: true


tracker:
    minimalPositionUpdateInterval: 5000 # in milliseconds
    #maximumShowPositionInterval: 30 * 60 * 1000; // 30 minutes in milliseconds

    #enables tracker log
    logger.enabled: false
    geocode.enabled: false

    map:
        forceSecure: false
        showLineDots: true  #by default will show the line dots
        amap_api_url: 'http://webapi.amap.com/maps?v=1.3&key=cfce41430c43afbb7bd2cdfab2d9a2ee' #change me!

    #Tracker connectors
    #GPS103 tracker
    gps103:
        enabled: true
        gps103.port: 5001

    #H02 tracker
    h02:
        enabled: false
        port: 5002

    #GT06 tracker
    gt06:
        enabled: false
        port: 5003

    #TK103 tracker setup
    tk103:
        enabled: false
        port: 5004
        #Not used configurations
        #address = 'localhost' - not used
        #resetDelay = 0

    #T55 tracker setup
    t55:
        enabled: false
        port: 5005

    #APRS APRS connector
    aprs:
        enabled: true
        address: 'rotate.aprs2.net'
        port: 14580
        call: 'foo'
        pass: 'bar'
        ##small china filter
        filter: 'r/31.864128/109.930590/1600'
        #blacklist = 'a,b,c,d,e'
        ##huge china filter
        #filter = 'r/36.045101/103.836093/2500'
        #filter = 'r/30.21/120.15/100' //range in Hangzhou 100KM
        #filter = 'p/B' //All callsign starts with B
        #filter = 'p/BG5HHP'
        data.daysToPreserve: 7